version: 1.0
api-version: 1.17
name: SheepOMagic
main: nl.devpieter.sheepomagic.SheepOMagic
description: Sheep o' Magic is a fun spigot plugin that makes sheep use their inner magic.
author: DevPieter
website: www.devpieter.nl